version: 2.1

orbs:
  node: circleci/node@5.1.0
  gh: circleci/github-cli@2.1.0

executors:
  node18:
    docker:
      - image: cimg/node:18.20

jobs:
  generate-codeowners:
    executor: node18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Generate dynamic CODEOWNERS
          command: npx ts-node scripts/generate-codeowners.ts
      - run:
          name: Check if CODEOWNERS changed
          command: |
            if ! git diff --quiet .github/CODEOWNERS; then
              echo "CODEOWNERS file changed, committing updates"
              git config user.name "CircleCI Bot"
              git config user.email "ci@superchain.dev"
              git add .github/CODEOWNERS
              git commit -m "Auto-update CODEOWNERS based on token changes [skip ci]"
              git push origin $CIRCLE_BRANCH
            else
              echo "CODEOWNERS file unchanged"
            fi
      - when:
          condition: on_fail
          steps:
            - gh/comment:
                gist: |
                  ❌ CODEOWNERS generation failed – see logs: $CIRCLE_BUILD_URL

  validate:
    executor: node18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run validate
      - when:
          condition: on_fail
          steps:
            - gh/comment:
                gist: |
                  ❌ superchain-tokenlist validation failed – see logs: $CIRCLE_BUILD_URL

  publish:
    executor: node18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build:package
      - run:
          name: Publish to npm
          command: npm publish --access public
      - run:
          name: Push to gh-pages
          command: ./scripts/push-gh-pages.sh

workflows:
  pr-checks:
    jobs:
      - generate-codeowners:
          context: superchain-ci
          filters:
            branches:
              ignore: main
      - validate:
          context: superchain-ci
          requires:
            - generate-codeowners
          filters:
            branches:
              ignore: main

  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: main
    jobs:
      - publish:
          context: superchain-ci 